export default {
  hostname: "example.com",
  systemAdministratorEmail: "administrator@example.com",
  // Paths to the key and certificate generated by Caddy, which must be provided here because they’re used for the email server.
  tls: {
    key: "/root/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/example.com/example.com.key",
    certificate:
      "/root/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/example.com/example.com.crt",
  },
  // The following is the default `dataDirectory`, but you may change it if necessary.
  // dataDirectory: "/root/kill-the-newsletter/data/",
  // Enable the following if you can. See https://hstspreload.org/.
  // hstsPreload: true,
  // Add some extra Caddyfile directives, for example, to redirect `www.example.com` to `example.com`.
  // extraCaddyfile: `
  //   www.example.com {
  //     redir https://example.com{uri}
  //   }
  // `,
};
