export default {
  hostname: "example.com",

  systemAdministratorEmail: "administrator@example.com",

  // Paths to the key and certificate generated by Caddy, which must be provided here because they’re used for the email server.
  tls: {
    key: "/root/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/example.com/example.com.key",
    certificate: "/root/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/example.com/example.com.crt",
  },

  // [Optional] The directory in which Kill the Newsletter! stores the database and files.
  // dataDirectory: "/root/kill-the-newsletter/data/",

  // [Optional] Enable HSTS Preload if you can: https://hstspreload.org/
  // hstsPreload: true,

  // [Optional] Caddyfile configuration: https://caddyserver.com
  // extraCaddyfile: `
  //   www.example.com {
  //     redir https://example.com{uri}
  //   }
  // `,
};
