on: push
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows
          - macos
          - ubuntu
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: latest
      - run: |
          npm install-ci-test
          npx package
          mv ../kill-the-newsletter.${{ matrix.os == 'windows' && 'zip' || 'tar.gz' }} ./kill-the-newsletter--${{ matrix.os }}--${{ startsWith(github.ref, 'refs/tags/v') && github.ref_name || github.sha }}.${{ matrix.os == 'windows' && 'zip' || 'tar.gz' }}
      - uses: actions/upload-artifact@main
        with:
          path: ./kill-the-newsletter--${{ matrix.os }}--${{ startsWith(github.ref, 'refs/tags/v') && github.ref_name || github.sha }}.${{ matrix.os == 'windows' && 'zip' || 'tar.gz' }}
          name: kill-the-newsletter--${{ matrix.os }}--${{ startsWith(github.ref, 'refs/tags/v') && github.ref_name || github.sha }}.${{ matrix.os == 'windows' && 'zip' || 'tar.gz' }}
      - if: ${{ matrix.os == 'ubuntu' && startsWith(github.ref, 'refs/tags/v') }}
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - if: ${{ matrix.os == 'ubuntu' && startsWith(github.ref, 'refs/tags/v') }}
        run: |
          cat >> ~/.ssh/known_hosts << "EOF"
            # $ ssh-keyscan kill-the-newsletter.com
            # kill-the-newsletter.com:22 SSH-2.0-OpenSSH_10.2p1 Ubuntu-2ubuntu3.5
            kill-the-newsletter.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBExsCv19jKNmLOz+o8qlq9X3ZIfufjM2S5VLGMRnMO+xzyf3sA8Vr4Mo5sDwzV7Le0dIdnrSXzytGLgqQPSpqzU=
            # kill-the-newsletter.com:22 SSH-2.0-OpenSSH_10.2p1 Ubuntu-2ubuntu3.5
            # kill-the-newsletter.com:22 SSH-2.0-OpenSSH_10.2p1 Ubuntu-2ubuntu3.5
            kill-the-newsletter.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCjKY8D+tljrGKJT4SyYZqCMEOQbQUqpXrZzDZWE4GItcD80WDgpQV0uyf6ioObHN7CYkDfK+KVV1xS/dNpKEgjqzc40CKIPqu2CZCQs6uWbTNUlgRM4eal9dRsUEY+tj65BJX3IMsnIArrVHfQEwDfXUOB/O+5zeyBdQbCB7eWb6XJvEJfY8Ayt8Hx/UC4Xg7C4wevbv2iWbursH8jwy6RAYyLxngei7Mr81H8GQ/cOZo370YcwZjxv0MvWmhs2OCVojvYTYkYBpTQhtwzBTAsR+j8Ol6IbHGfd83DEucXzcG1OgID1SJ2/GymVORYQUPYUrrMTT8n7Nuwlg0fUfJlTSyOXa3RAC5xrRjCxNnDyArKlc+OEYe/eALLuoLLE9OhBey4P5P1yEqqbzDjX7WQyxIbMcfcrp7OXvGsAqsVVu/8BLfeVIuLIW2H0KVzZs3MSVBRza1DB3cgN5wJn+EpuQGBI4o+48qT+ihnrrSbxwflDAC93pRY/SxzfZK1f+0=
            # kill-the-newsletter.com:22 SSH-2.0-OpenSSH_10.2p1 Ubuntu-2ubuntu3.5
            kill-the-newsletter.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFV1haTYqLlxgtSrNPYC2BSkubvUL2l3pOfVK7BCA7L3
            # kill-the-newsletter.com:22 SSH-2.0-OpenSSH_10.2p1 Ubuntu-2ubuntu3.5
          EOF
          rsync -a ./kill-the-newsletter--ubuntu--${{ github.ref_name }}.tar.gz root@kill-the-newsletter.com:/mnt/kill-the-newsletter/kill-the-newsletter--ubuntu--${{ github.ref_name }}.tar.gz
          ssh root@kill-the-newsletter.com << "EOF"
            mkdir -p /mnt/kill-the-newsletter/kill-the-newsletter/
            rm -rf /mnt/kill-the-newsletter/kill-the-newsletter--deploy/
            mkdir /mnt/kill-the-newsletter/kill-the-newsletter--deploy/
            mv /mnt/kill-the-newsletter/kill-the-newsletter--ubuntu--${{ github.ref_name }}.tar.gz /mnt/kill-the-newsletter/kill-the-newsletter--deploy/kill-the-newsletter--ubuntu--${{ github.ref_name }}.tar.gz
            cd /mnt/kill-the-newsletter/kill-the-newsletter--deploy/
            tar -xzf ./kill-the-newsletter--ubuntu--${{ github.ref_name }}.tar.gz
            cp /mnt/kill-the-newsletter/kill-the-newsletter--deploy/kill-the-newsletter/_/configuration/kill-the-newsletter.com.mjs /mnt/kill-the-newsletter/kill-the-newsletter/configuration.mjs
            systemctl stop kill-the-newsletter || true
            cp /mnt/kill-the-newsletter/kill-the-newsletter--deploy/kill-the-newsletter/_/configuration/kill-the-newsletter.service /etc/systemd/system/kill-the-newsletter.service
            systemctl daemon-reload
            mv /mnt/kill-the-newsletter/kill-the-newsletter/kill-the-newsletter/ /mnt/kill-the-newsletter/kill-the-newsletter--deploy/kill-the-newsletter--old/ || true
            mv /mnt/kill-the-newsletter/kill-the-newsletter--deploy/kill-the-newsletter/ /mnt/kill-the-newsletter/kill-the-newsletter/kill-the-newsletter/
            systemctl start kill-the-newsletter
            systemctl enable kill-the-newsletter
            rm -rf /mnt/kill-the-newsletter/kill-the-newsletter--deploy/
          EOF
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@main
      - uses: softprops/action-gh-release@master
        with:
          files: ./**/*.*
